spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  mail:
    host: smtp.qq.com
    username: 286284737@qq.com
    password: rmzdmoyfmkgebjih
  boot:
    admin:
      notify:
        mail:
#          to: wzqsoloman914@gmail.com
          from: 286284737@qq.com
          to: 286284737@qq.com
server:
  port: 10010
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
