spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#  redis:
#    host: localhost
#    port: 6379
server:
  port: 8010
yibu:
  auth:
    jwt:
      pubkeyPath: D:\\rsa\\yibu\\rsa.pub
      prikeyPath: D:\\rsa\\yibu\\rsa.pri
      secret: sf3423jsdf#3$@FDS32
      expire: 30
      cookieName: YIBU_TOKEN