spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          management:
            context-path: '${server.servlet.context-path}/actuator'
  # 连接admin server
  boot:
    admin:
      client:
        url: http://loaclhost:10086/admin-server
#        instance:
#          service-url: admin-client
#          management-base-url: admin-client
server:
  port: 10020
  servlet:
    context-path: /admin-client
# 设置暴露的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
